version: 2.1

parameters:
  specgen-version:
    type: string
    default: 1.10.32
  tests-version:
    type: string
    default: "1.0"

jobs:
  service-go:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/test-service-go
    steps:
      - checkout
      - run:
          name: Build
          command: ./build.sh

      - run:
          name: Start service-go
          command: ./dist/linux_amd64/service-go --port 8081
          background: true
      - wait-url:
          url: http://localhost:8081/

      - run:
          name: Install service-tests
          command: |
            curl -L https://github.com/specgen-io/service-tests/releases/download/<< pipeline.parameters.tests-version >>/service-tests_linux_amd64.zip > service-tests.zip
            unzip -o service-tests.zip
            ls -la

      - run:
          name: Install go-junit-report
          command: |
            curl -L https://github.com/vsapronov/go-junit-report/releases/download/latest/go-junit-report_linux_amd64.zip > go-junit-report.zip
            unzip -o go-junit-report.zip
            ls -la
      - run:
          name: Run tests
          command: |
            mkdir -p ./test-results
            ./service-tests -test.v 2>&1 | ./go-junit-report > ./test-results/go-test-report.xml

      - store_artifacts:
          path: ./zips
          destination: zips
      - store_artifacts:
          path: ./dist
          destination: test-service-go
      - store_artifacts:
          path: ./test-results
          destination: go-test-report
      - store_test_results:
          path: ./test-results
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - run:
          name: Release
          command: |
            if [ $CIRCLE_BRANCH = "main" ]; then
              ./release.sh << pipeline.parameters.specgen-version >> ${GITHUB_TOKEN}
            else
              echo "Will not release - not running on main branch"
            fi

workflows:
  service-go:
    jobs:
      - service-go:
          context: specgen
